CREATE DATABASE "JDBC";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ERS_admin;

-- DROP TABLE ERS_REIMBURSEMENT, ERS_USERS, ERS_REIMBURSEMENT_STATUS, ERS_REIMBURSEMENT_TYPE, ERS_USER_ROLES;

CREATE TABLE ERS_REIMBURSEMENT(
   REIMB_ID				INT				NOT NULL,
   REIMB_AMOUNT 		INT				NOT NULL,
   REIMB_SUBMITTED 		DATE			NOT NULL,
   REIMB_RESOLVED		DATE			NOT NULL,
   REIMB_DESCRIPTION	VARCHAR(250)	NOT NULL,
   REIMB_RECEIPT		VARCHAR(250)	NOT NULL,
   REIMB_AUTHOR			INT				NOT NULL,
   REIMB_RESOLVER		INT				NOT NULL,
   REIMB_STATUS_ID		INT				NOT NULL,
   REIMB_TYPE_ID		INT				NOT NULL,
   PRIMARY KEY (REIMB_ID)
);

ALTER TABLE ERS_REIMBURSEMENT 
ADD FOREIGN KEY (REIMB_AUTHOR) REFERENCES ERS_USERS (ERS_USERS_ID);

ALTER TABLE ERS_REIMBURSEMENT 
ADD FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS (ERS_USERS_ID);

ALTER TABLE ERS_REIMBURSEMENT 
ADD FOREIGN KEY (REIMB_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID);

ALTER TABLE ERS_REIMBURSEMENT 
ADD FOREIGN KEY (REIMB_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID);

-- NEW TABLE --------------------------------------------------------------------------------------------------------------

CREATE TABLE ERS_USERS(
   ERS_USERS_ID			INT				NOT NULL,
   ERS_USERNAME 		VARCHAR(50)		NOT null UNIQUE,
   ERS_PASSWORD 		VARCHAR(50)		NOT NULL,
   USER_FIRST_NAME		VARCHAR(100)	NOT NULL,
   USER_LAST_NAME		VARCHAR(100)	NOT NULL,
   USER_EMAIL			VARCHAR(150)	NOT null UNIQUE,
   USER_ROLE_ID			INT				NOT NULL,
   PRIMARY KEY (ERS_USERS_ID) 
);

ALTER TABLE ERS_USERS 
ADD FOREIGN KEY (USER_ROLE_ID) REFERENCES ERS_USER_ROLES (ERS_USER_ROLE_ID);

-- NEW TABLE --------------------------------------------------------------------------------------------------------------

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
   REIMB_STATUS_ID		INT				NOT NULL,
   REIMB_STATUS			VARCHAR(10)		NOT NULL,
   PRIMARY KEY (REIMB_STATUS_ID) 
);

-- NEW TABLE --------------------------------------------------------------------------------------------------------------

CREATE TABLE ERS_REIMBURSEMENT_TYPE(
   REIMB_TYPE_ID		INT				NOT NULL,
   REIMB_TYPE			VARCHAR(10)		NOT NULL,
   PRIMARY KEY (REIMB_TYPE_ID) 
);

-- NEW TABLE --------------------------------------------------------------------------------------------------------------

CREATE TABLE ERS_USER_ROLES(
   ERS_USER_ROLE_ID		INT				NOT NULL,
   USER_ROLE			VARCHAR(10)		NOT NULL,
   PRIMARY KEY (ERS_USER_ROLE_ID) 
);